apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: efklog
spec:
  type: LoadBalancer
  selector:
    kibana.k8s.elastic.co/name: quickstart
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP

